image:
  repository: artifactory.dagility.com/docker/vdcheckdeploya-frontend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: vdcheckdeploya-frontend-cattle-impersonation-system.dagility.com
    paths:
    - /
serviceAccount:
  create: false
